name: Deploy Kafka Topics and ACLs

on:
  push:
    paths:
      - 'DEV*/**'  # Detect changes in any my_topics_* directories
  pull_request:
    paths:
      - 'DEV*/**'
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy-topics-acls:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Get the list of changed files
    - name: Check for modified files
      id: file_check
      run: |
        # Get the list of files modified in this commit
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        cat changed_files.txt

