name: Deploy Kafka Topics and ACLs

on:
  push:
    paths:
      - 'DEV*/**'  # Detect changes in any my_topics_* directories
  pull_request:
    paths:
      - 'DEV*/**'
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy-topics-acls:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Get the list of changed files
    - name: Check for modified files
      id: file_check
      run: |
        # Fallback if github.event.before is missing or bad
        if [ -z "${{ github.event.before }}" ]; then
          echo "No prior commit found, using HEAD~1 as the fallback."
          git diff --name-only HEAD~1 > changed_files.txt
        else
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt || git diff --name-only HEAD~1 > changed_files.txt
        fi

        # Display the modified files (for debugging)
        cat changed_files.txt

